feat: add instructions for Ansible installation.
Hexlet/ru-instructions pull request #27
Opened 2023-04-25 18:22 UTC by DmitriiGoltsov

Перевёл и сократил официальную инструкцию по установке Ansible. Добавил её в файл ansible.md. 

В инструкции оставил только актуальные для учащихся Хекслета шаги. Кроме того сделал ссылки на установку Пайтона и WSL. В README.md добавил ссылку на новое руководство.

closes #25

2023-04-26 19:59 UTC, ssssank commented
Пробегись, пожалуйста, по тексту и поправь опечатки, лучше всего загнать текст в главред и проверку грамматики. И ещё, мы не используем Вы с большой буквы

2023-04-26 19:59 UTC, ssssank commented
@ashikov посмотри, пожалуйста, тоже на правильность и необходимость шагов в инструкции

2023-04-27 08:12 UTC, DmitriiGoltsov commented
> Пробегись, пожалуйста, по тексту и поправь опечатки, лучше всего загнать текст в главред и проверку грамматики. И ещё, мы не используем Вы с большой буквы

Хорошо. Ещё раз вычитаю текст. "Вы" поправлю

2023-04-28 07:31 UTC, ashikov requested changes
Немного пробежался по основным моментам. @ssssank тут нужна будет финальная вычитка редактора.

2023-04-28 07:31 UTC, ashikov commented on ansible.md
> +В качестве узла управления (так называется машина, на которой запускается Ansible) Вы можете исопользовать практически любую UNIX-подобную систему с установленным [Python](/python.md) версии 3.9 или
Думаю можно не писать про разные операционные системы. Курсы у нас ориентированы на выполнение в Ubuntu. Под WSL оно работает также, с очень незначительными нюансами.

2023-04-28 07:31 UTC, ashikov commented on ansible.md
> +## Выбор версии Ansible
Мы не паримся и сразу устанавливаем ansible.

2023-04-28 07:31 UTC, ashikov commented on ansible.md
> +### Обнаружение Python
Куда сохранить пут и зачем? Тут не совсем понятно. Точнее мне-то понятно. Но нужно держать в голове, что мы пишем инструкцию для новичка.

2023-04-28 07:31 UTC, ashikov commented on ansible.md
> +Выясните и сохраните путь к том интерпретатору Python, который Вы хотите использовать для запуска Ansible. Последующая инстркция отсылает к нему как `python3`. К примеру, если python, который Вы хоти
> Последующая инстркция отсылает к нему как `python3`.

Непонятное предложение

2023-04-28 07:31 UTC, ashikov commented on ansible.md
> +Используйте нижеследующую комманду для проверки, установлен ли `pip` для Вашего Python:
Чтобы проверить установлен ли `pip` используйте следующую команду:

2023-04-28 07:31 UTC, ashikov commented on ansible.md
> +$ python3 -m pip show ansible
А почему не проверить напрямую, а не через pip?

2023-04-28 13:44 UTC, DmitriiGoltsov commented on ansible.md
> +В качестве узла управления (так называется машина, на которой запускается Ansible) Вы можете исопользовать практически любую UNIX-подобную систему с установленным [Python](/python.md) версии 3.9 или
Убрал избыточную информацию про дистрибутивы, макОс и WSL.

2023-04-28 13:44 UTC, DmitriiGoltsov commented on ansible.md
> +## Выбор версии Ansible
Убрал требования к управляемому узлу.

2023-04-28 13:45 UTC, DmitriiGoltsov commented on ansible.md
> +### Обнаружение Python
Упростил эту и связанную с нею части.

2023-04-28 13:45 UTC, DmitriiGoltsov commented on ansible.md
> +Используйте нижеследующую комманду для проверки, установлен ли `pip` для Вашего Python:
Ок

2023-04-28 13:47 UTC, DmitriiGoltsov commented on ansible.md
> +$ python3 -m pip show ansible
Я добавил оба варианта проверки в инструкцию. 

Изначально меня смутило, что прямая проверка, судя по официальной инструкции, проверяет ansible-core, а проверка через pip проверяет всё.

2023-04-28 13:50 UTC, DmitriiGoltsov commented
> Пробегись, пожалуйста, по тексту и поправь опечатки, лучше всего загнать текст в главред и проверку грамматики. И ещё, мы не используем Вы с большой буквы

Убрал выявленные ошибки, подправил грамматику, упростил текст, где об этом попросили. Вы или убрал вовсе или сделал с маленькой буквы.

2023-05-02 14:49 UTC, ssssank commented
Теперь нужно решить конфликты, так как появились другие инструкции в README.md.

2023-05-02 15:22 UTC, closed without merging